-- Tables
-- Generated at: 2026-05-08T22:36:36.285888+00:00
-- Schema: public

CREATE TABLE IF NOT EXISTS public."actimize_alert_callbacks" (
    "callback_id" bigint DEFAULT nextval('actimize_alert_callbacks_callback_id_seq'::regclass) NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "unique_key" text NOT NULL,
    "normalized_unique_key" text NOT NULL,
    "alert_id" text NOT NULL,
    "screening_cd" text,
    "status_cd" text NOT NULL,
    "update_timestamp" text,
    "source_system_cd" text,
    "tenant_cd" text,
    "matched_count" integer DEFAULT 0 NOT NULL,
    "details_json" text
);

CREATE TABLE IF NOT EXISTS public."actimize_screening_type_mappings" (
    "Search_Definition_ID" character varying(50) NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "search_definition_name" character varying(255) DEFAULT ''::text NOT NULL,
    "Screening_Type" character varying(10) DEFAULT ''::text NOT NULL,
    "display_order" integer DEFAULT 1000 NOT NULL
);

CREATE TABLE IF NOT EXISTS public."api_access_logs" (
    "access_id" bigint DEFAULT nextval('api_access_logs_access_id_seq'::regclass) NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "correlation_id" text,
    "request_method" text NOT NULL,
    "request_path" text NOT NULL,
    "query_string" text,
    "status_code" integer NOT NULL,
    "duration_ms" integer NOT NULL,
    "client_ip" text,
    "user_agent" text,
    "user_name" text,
    "auth_state" text,
    "details_json" text,
    "user_ref_id" bigint
);

CREATE TABLE IF NOT EXISTS public."app_users" (
    "user_id" bigint NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "name" character varying(255),
    "email" character varying(50),
    "old_id" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."audit_events" (
    "event_id" bigint DEFAULT nextval('audit_events_event_id_seq'::regclass) NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "user_name" text,
    "action" text NOT NULL,
    "entity_type" text,
    "entity_id" text,
    "details_json" text,
    "user_ref_id" bigint
);

CREATE TABLE IF NOT EXISTS public."batch_file_uploads" (
    "upload_id" text NOT NULL,
    "schedule_id" integer,
    "job_id" text,
    "file_name" text NOT NULL,
    "s3_bucket" text,
    "s3_key" text,
    "s3_uri" text,
    "queries_s3_bucket" text,
    "queries_s3_key" text,
    "queries_s3_uri" text,
    "file_hash" text,
    "record_count" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "user_ref_id" bigint,
    "job_seq_id" bigint
);

CREATE TABLE IF NOT EXISTS public."business_units" (
    "business_unit_code" character varying(50) NOT NULL,
    "business_unit_name" character varying(255) NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."business_unit_screening_types" (
    "business_unit_code" character varying(50) NOT NULL,
    "Screening_Type" character varying(10) NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Batch_Schedule" (
    "schedule_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "batch_name" text NOT NULL,
    "queries_json" text NOT NULL,
    "screening_types_json" text NOT NULL,
    "mock_screening" boolean DEFAULT false NOT NULL,
    "schedule_frequency" text DEFAULT 'DAILY'::text NOT NULL,
    "timezone" text NOT NULL,
    "run_hour" integer NOT NULL,
    "run_minute" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "last_run_at" timestamp with time zone,
    "next_run_at" timestamp with time zone DEFAULT now() NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "source_upload_id" text,
    "source_file_name" text,
    "source_s3_uri" text,
    "business_unit_code" character varying(50),
    "user_ref_id" bigint
);

CREATE TABLE IF NOT EXISTS public."external_api_errors" (
    "error_id" bigint DEFAULT nextval('external_api_errors_error_id_seq'::regclass) NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "provider" text NOT NULL,
    "operation" text,
    "endpoint" text,
    "status_code" integer,
    "user_name" text,
    "item_key" text,
    "error_text" text NOT NULL,
    "details_json" text,
    "user_ref_id" bigint,
    "job_seq_id" bigint
);

CREATE TABLE IF NOT EXISTS public."job_items" (
    "job_id" text NOT NULL,
    "item_key" text NOT NULL,
    "request_json" text NOT NULL,
    "response_json" text,
    "status" text NOT NULL,
    "error_text" text,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "parsed_status" character varying(16) DEFAULT 'PENDING'::character varying NOT NULL,
    "job_seq_id" bigint NOT NULL,
    "user_ref_id" bigint
);

CREATE TABLE IF NOT EXISTS public."job_metadata" (
    "job_id" text NOT NULL,
    "mode" text DEFAULT 'BATCH'::text NOT NULL,
    "screening_types_json" text DEFAULT '[]'::text NOT NULL,
    "mock_screening" boolean DEFAULT false NOT NULL,
    "batch_name" text,
    "file_name" text,
    "daily_screening" boolean DEFAULT false NOT NULL,
    "schedule_frequency" text,
    "daily_schedule_id" integer,
    "query_count" integer DEFAULT 0 NOT NULL,
    "deferred_until" text,
    "business_unit_code" character varying(50),
    "job_seq_id" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public."job_schedule_notifications" (
    "job_id" text NOT NULL,
    "schedule_id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "job_seq_id" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public."jobs" (
    "job_id" text NOT NULL,
    "status" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "total_items" integer NOT NULL,
    "source_schedule_id" integer,
    "source_upload_id" text,
    "job_seq_id" bigint DEFAULT nextval('jobs_job_seq_id_seq'::regclass) NOT NULL,
    "user_ref_id" bigint
);

CREATE TABLE IF NOT EXISTS public."schedule_notifications" (
    "notification_id" bigint DEFAULT nextval('schedule_notifications_notification_id_seq'::regclass) NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "user_name" text,
    "email" text,
    "schedule_id" integer,
    "job_id" text,
    "title" text NOT NULL,
    "message" text NOT NULL,
    "summary_json" text,
    "user_ref_id" bigint,
    "job_seq_id" bigint
);

CREATE TABLE IF NOT EXISTS public."schedule_record_state" (
    "schedule_id" integer NOT NULL,
    "record_hash" text NOT NULL,
    "first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
    "last_screened_at" timestamp with time zone DEFAULT now() NOT NULL,
    "last_job_id" text,
    "last_job_seq_id" bigint
);

CREATE TABLE IF NOT EXISTS public."schedule_subscriptions" (
    "subscription_id" text NOT NULL,
    "schedule_id" integer NOT NULL,
    "email" text NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "user_ref_id" bigint
);

CREATE TABLE IF NOT EXISTS public."user_business_units" (
    "business_unit_code" character varying(50) NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "user_ref_id" bigint NOT NULL
);
