-- Roles and group memberships extracted from PostgreSQL
-- Generated at 2026-03-10T00:46:46.632020+00:00
-- Note: Password hashes are not included (no access to pg_authid.rolpassword).

CREATE ROLE "rds_ad" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 VALID UNTIL 'infinity';

CREATE ROLE "rds_extension" WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 VALID UNTIL 'infinity';

CREATE ROLE "rds_iam" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 VALID UNTIL 'infinity';

CREATE ROLE "rds_password" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 VALID UNTIL 'infinity';

CREATE ROLE "rds_replication" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 VALID UNTIL 'infinity';

CREATE ROLE "rds_reserved" WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 VALID UNTIL 'infinity';

CREATE ROLE "rds_superuser" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 VALID UNTIL 'infinity';

CREATE ROLE "rdsadmin" WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS CONNECTION LIMIT -1 VALID UNTIL 'infinity';

CREATE ROLE "screening_admin" WITH NOSUPERUSER INHERIT CREATEROLE CREATEDB LOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 VALID UNTIL 'infinity';

-- Role memberships
GRANT "rds_password" TO "rds_superuser" WITH ADMIN OPTION;
GRANT "rds_replication" TO "rds_superuser" WITH ADMIN OPTION;
GRANT "rds_superuser" TO "screening_admin";
