-- Generated from AWS RDS PostgreSQL
-- Generated at UTC: 2026-05-24T21:06:19Z
-- Source host: screening-postgres-dev.czqoaymkk4o6.us-east-2.rds.amazonaws.com
-- Source db: screening
-- Contains: full schema DDL + reference data DML for selected reference tables

--
-- PostgreSQL database dump
--

\restrict 1Yw289Odu8iIAL6k1LkbuDpT7ZsF2s3jpYXgCgcxysHB5PkTcAiWxQJUnFVDF8o

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Debian 17.9-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actimize_alert_callbacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.actimize_alert_callbacks (
    callback_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    unique_key character varying(255) NOT NULL,
    normalized_unique_key character varying(255) NOT NULL,
    alert_id character varying(255) NOT NULL,
    screening_cd character varying(16),
    status_cd character(1) NOT NULL,
    update_timestamp timestamp with time zone,
    source_system_cd character varying(64),
    tenant_cd character varying(64),
    matched_count integer DEFAULT 0 NOT NULL,
    details_json jsonb,
    CONSTRAINT chk_actimize_status_cd CHECK ((status_cd = ANY (ARRAY['F'::bpchar, 'T'::bpchar])))
);


--
-- Name: actimize_alert_callbacks_callback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.actimize_alert_callbacks_callback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: actimize_alert_callbacks_callback_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.actimize_alert_callbacks_callback_id_seq OWNED BY public.actimize_alert_callbacks.callback_id;


--
-- Name: actimize_screening_type_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.actimize_screening_type_mappings (
    "Search_Definition_ID" character varying(50) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    search_definition_name character varying(255) DEFAULT ''::text NOT NULL,
    "Screening_Type" character varying(10) DEFAULT ''::text NOT NULL,
    display_order integer DEFAULT 1000 NOT NULL
);


--
-- Name: api_access_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_access_logs (
    access_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    correlation_id character varying(128),
    request_method character varying(16) NOT NULL,
    request_path text NOT NULL,
    query_string text,
    status_code integer NOT NULL,
    duration_ms integer NOT NULL,
    client_ip character varying(64),
    user_agent text,
    user_name character varying(255),
    auth_state character varying(32),
    details_json jsonb,
    user_ref_id bigint
);


--
-- Name: api_access_logs_access_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.api_access_logs_access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: api_access_logs_access_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.api_access_logs_access_id_seq OWNED BY public.api_access_logs.access_id;


--
-- Name: app_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users (
    user_id bigint NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    name character varying(255),
    email character varying(50),
    old_id character varying(128) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: app_users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_events (
    event_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_name character varying(255),
    action character varying(64) NOT NULL,
    entity_type character varying(64),
    entity_id character varying(255),
    details_json jsonb,
    user_ref_id bigint
);


--
-- Name: audit_events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_events_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_events_event_id_seq OWNED BY public.audit_events.event_id;


--
-- Name: batch_file_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_file_uploads (
    upload_id character varying(128) NOT NULL,
    schedule_id integer,
    file_name character varying(512) NOT NULL,
    s3_bucket character varying(128),
    s3_key character varying(1024),
    s3_uri text,
    queries_s3_bucket character varying(128),
    queries_s3_key character varying(1024),
    queries_s3_uri text,
    file_hash character varying(128),
    record_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    user_ref_id bigint,
    job_id bigint
);


--
-- Name: business_unit_screening_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_unit_screening_types (
    business_unit_code character varying(50) NOT NULL,
    "Screening_Type" character varying(10) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: business_units; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_units (
    business_unit_code character varying(50) NOT NULL,
    business_unit_name character varying(255) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: daily_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_schedules (
    schedule_id integer NOT NULL,
    batch_name character varying(255) NOT NULL,
    queries_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    screening_types_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    mock_screening boolean DEFAULT false NOT NULL,
    schedule_frequency character varying(32) DEFAULT 'DAILY'::text NOT NULL,
    timezone character varying(64) NOT NULL,
    run_hour integer NOT NULL,
    run_minute integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_run_at timestamp with time zone,
    next_run_at timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    source_upload_id character varying(128),
    source_file_name character varying(512),
    source_s3_uri text,
    business_unit_code character varying(50),
    user_ref_id bigint,
    CONSTRAINT chk_daily_schedules_schedule_frequency CHECK ((upper((schedule_frequency)::text) = ANY (ARRAY['DAILY'::text, 'WEEKLY'::text, 'MONTHLY'::text, 'QUARTERLY'::text, 'ONCE'::text])))
);


--
-- Name: daily_schedules_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_schedules ALTER COLUMN schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_schedules_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: external_api_errors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.external_api_errors (
    error_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    provider character varying(64) NOT NULL,
    operation character varying(64),
    endpoint text,
    status_code integer,
    user_name character varying(255),
    item_key character varying(128),
    error_text text NOT NULL,
    details_json jsonb,
    user_ref_id bigint,
    job_id bigint
);


--
-- Name: external_api_errors_error_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.external_api_errors_error_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: external_api_errors_error_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.external_api_errors_error_id_seq OWNED BY public.external_api_errors.error_id;


--
-- Name: job_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_items (
    item_key character varying(128) NOT NULL,
    request_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    response_json jsonb,
    status character varying(16) NOT NULL,
    error_text text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    parsed_status character varying(16) DEFAULT 'PENDING'::character varying NOT NULL,
    job_id bigint NOT NULL,
    user_ref_id bigint,
    CONSTRAINT chk_job_items_status CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT job_items_parsed_status_check CHECK (((parsed_status)::text = ANY ((ARRAY['CLEAR'::character varying, 'POTENTIAL'::character varying, 'PENDING'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: job_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_metadata (
    mode character varying(16) DEFAULT 'BATCH'::text NOT NULL,
    screening_types_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    mock_screening boolean DEFAULT false NOT NULL,
    batch_name character varying(255),
    file_name character varying(512),
    daily_screening boolean DEFAULT false NOT NULL,
    schedule_frequency character varying(32),
    daily_schedule_id integer,
    query_count integer DEFAULT 0 NOT NULL,
    deferred_until timestamp with time zone,
    business_unit_code character varying(50),
    job_id bigint NOT NULL,
    CONSTRAINT chk_job_metadata_mode CHECK (((mode)::text = ANY ((ARRAY['BATCH'::character varying, 'SINGLE'::character varying])::text[])))
);


--
-- Name: job_schedule_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_schedule_notifications (
    schedule_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    job_id bigint NOT NULL
);


--
-- Name: jobs_job_seq_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.jobs_job_seq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    status character varying(16) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    total_items integer NOT NULL,
    source_schedule_id integer,
    source_upload_id character varying(128),
    job_id bigint DEFAULT nextval('public.jobs_job_seq_id_seq'::regclass) NOT NULL,
    user_ref_id bigint,
    CONSTRAINT chk_jobs_status CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: mv_daily_schedule_batch_runs; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.mv_daily_schedule_batch_runs AS
 SELECT j.job_id,
    COALESCE(jm.daily_schedule_id, j.source_schedule_id) AS schedule_id,
    upper((COALESCE(j.status, ''::character varying))::text) AS job_status,
    j.created_at,
    j.updated_at,
    j.total_items,
    j.source_upload_id,
    j.user_ref_id,
    au.old_id AS user_id,
    COALESCE(au.name, au.old_id) AS user_name,
    COALESCE(NULLIF((jm.batch_name)::text, ''::text), NULLIF((ds.batch_name)::text, ''::text), NULLIF((jm.file_name)::text, ''::text), NULLIF((bu.file_name)::text, ''::text), 'Scheduled Batch'::text) AS batch_name,
    NULLIF(COALESCE(NULLIF((jm.schedule_frequency)::text, ''::text), NULLIF((ds.schedule_frequency)::text, ''::text)), ''::text) AS schedule_frequency,
    NULLIF(COALESCE(NULLIF((bu.file_name)::text, ''::text), NULLIF((ds.source_file_name)::text, ''::text), NULLIF((jm.file_name)::text, ''::text)), ''::text) AS source_file_name,
    COALESCE(js.completed_items, (0)::bigint) AS completed_items,
    COALESCE(js.failed_items, (0)::bigint) AS failed_items,
    COALESCE(js.pending_items, (0)::bigint) AS pending_items,
    COALESCE(js.processing_items, (0)::bigint) AS processing_items
   FROM (((((public.jobs j
     LEFT JOIN public.app_users au ON ((au.user_id = j.user_ref_id)))
     LEFT JOIN public.job_metadata jm ON ((jm.job_id = j.job_id)))
     LEFT JOIN public.daily_schedules ds ON ((ds.schedule_id = COALESCE(jm.daily_schedule_id, j.source_schedule_id))))
     LEFT JOIN public.batch_file_uploads bu ON (((bu.upload_id)::text = (j.source_upload_id)::text)))
     LEFT JOIN ( SELECT job_items.job_id,
            sum(
                CASE
                    WHEN ((job_items.status)::text = 'COMPLETED'::text) THEN 1
                    ELSE 0
                END) AS completed_items,
            sum(
                CASE
                    WHEN ((job_items.status)::text = 'FAILED'::text) THEN 1
                    ELSE 0
                END) AS failed_items,
            sum(
                CASE
                    WHEN ((job_items.status)::text = 'QUEUED'::text) THEN 1
                    ELSE 0
                END) AS pending_items,
            sum(
                CASE
                    WHEN ((job_items.status)::text = 'PROCESSING'::text) THEN 1
                    ELSE 0
                END) AS processing_items
           FROM public.job_items
          GROUP BY job_items.job_id) js ON ((js.job_id = j.job_id)))
  WHERE ((COALESCE(jm.daily_schedule_id, j.source_schedule_id) IS NOT NULL) AND (upper((COALESCE(jm.mode, 'BATCH'::character varying))::text) = 'BATCH'::text))
  WITH NO DATA;


--
-- Name: mv_user_recent_results; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.mv_user_recent_results AS
 SELECT j.user_ref_id,
    au.old_id AS user_id,
    COALESCE(au.name, au.old_id) AS user_name,
    j.job_id,
    ji.item_key,
    COALESCE(ji.updated_at, j.updated_at, j.created_at) AS sort_ts,
        CASE
            WHEN (upper(COALESCE(NULLIF((ji.parsed_status)::text, ''::text), ''::text)) = ANY (ARRAY['CLEAR'::text, 'POTENTIAL'::text, 'PENDING'::text, 'FAILED'::text])) THEN upper((ji.parsed_status)::text)
            WHEN (upper((COALESCE(ji.status, ''::character varying))::text) = ANY (ARRAY['QUEUED'::text, 'PROCESSING'::text])) THEN 'PENDING'::text
            WHEN (upper((COALESCE(ji.status, ''::character varying))::text) = 'FAILED'::text) THEN 'FAILED'::text
            WHEN (ji.response_json IS NULL) THEN 'FAILED'::text
            WHEN (upper(COALESCE((ji.response_json ->> 'engine_message'::text), ''::text)) = 'PM'::text) THEN 'POTENTIAL'::text
            WHEN (upper(COALESCE((ji.response_json ->> 'engine_message'::text), ''::text)) = 'NM'::text) THEN 'CLEAR'::text
            ELSE 'CLEAR'::text
        END AS parsed_status
   FROM ((public.jobs j
     LEFT JOIN public.app_users au ON ((au.user_id = j.user_ref_id)))
     JOIN public.job_items ji ON ((ji.job_id = j.job_id)))
  WHERE (j.user_ref_id IS NOT NULL)
  WITH NO DATA;


--
-- Name: mv_user_result_summary_counts; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.mv_user_result_summary_counts AS
 SELECT user_ref_id,
    max((user_id)::text) AS user_id,
    count(*) AS total,
    sum(
        CASE
            WHEN (parsed_status = 'CLEAR'::text) THEN 1
            ELSE 0
        END) AS clear,
    sum(
        CASE
            WHEN (parsed_status = 'POTENTIAL'::text) THEN 1
            ELSE 0
        END) AS potential,
    sum(
        CASE
            WHEN (parsed_status = 'PENDING'::text) THEN 1
            ELSE 0
        END) AS pending,
    sum(
        CASE
            WHEN (parsed_status = 'FAILED'::text) THEN 1
            ELSE 0
        END) AS failed
   FROM public.mv_user_recent_results
  GROUP BY user_ref_id
  WITH NO DATA;


--
-- Name: mv_user_submission_jobs; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.mv_user_submission_jobs AS
 SELECT j.job_id,
    j.user_ref_id,
    j.created_at,
    j.total_items,
    j.source_schedule_id,
    j.source_upload_id,
    au.old_id AS user_id,
    COALESCE(au.name, au.old_id) AS user_name,
    jm.mode,
    jm.screening_types_json,
    jm.mock_screening,
    jm.batch_name,
    jm.file_name,
    jm.daily_screening,
    jm.schedule_frequency,
    jm.daily_schedule_id,
    jm.business_unit_code,
    bu.file_name AS upload_file_name,
    bu.s3_uri AS upload_s3_uri
   FROM (((public.jobs j
     LEFT JOIN public.app_users au ON ((au.user_id = j.user_ref_id)))
     LEFT JOIN public.job_metadata jm ON ((jm.job_id = j.job_id)))
     LEFT JOIN public.batch_file_uploads bu ON (((bu.upload_id)::text = (j.source_upload_id)::text)))
  WITH NO DATA;


--
-- Name: schedule_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_notifications (
    notification_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_name character varying(255),
    email character varying(254),
    schedule_id integer,
    title character varying(255) NOT NULL,
    message text NOT NULL,
    summary_json jsonb,
    user_ref_id bigint,
    job_id bigint
);


--
-- Name: schedule_notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.schedule_notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: schedule_notifications_notification_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.schedule_notifications_notification_id_seq OWNED BY public.schedule_notifications.notification_id;


--
-- Name: schedule_record_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_record_state (
    schedule_id integer NOT NULL,
    record_hash character varying(128) NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_screened_at timestamp with time zone DEFAULT now() NOT NULL,
    last_job_id bigint
);


--
-- Name: schedule_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_subscriptions (
    subscription_id character varying(128) NOT NULL,
    schedule_id integer NOT NULL,
    email character varying(254) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_ref_id bigint
);


--
-- Name: user_business_units; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_business_units (
    business_unit_code character varying(50) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_ref_id bigint NOT NULL
);


--
-- Name: actimize_alert_callbacks callback_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actimize_alert_callbacks ALTER COLUMN callback_id SET DEFAULT nextval('public.actimize_alert_callbacks_callback_id_seq'::regclass);


--
-- Name: api_access_logs access_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_access_logs ALTER COLUMN access_id SET DEFAULT nextval('public.api_access_logs_access_id_seq'::regclass);


--
-- Name: audit_events event_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_events ALTER COLUMN event_id SET DEFAULT nextval('public.audit_events_event_id_seq'::regclass);


--
-- Name: external_api_errors error_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_api_errors ALTER COLUMN error_id SET DEFAULT nextval('public.external_api_errors_error_id_seq'::regclass);


--
-- Name: schedule_notifications notification_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_notifications ALTER COLUMN notification_id SET DEFAULT nextval('public.schedule_notifications_notification_id_seq'::regclass);


--
-- Name: actimize_alert_callbacks actimize_alert_callbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actimize_alert_callbacks
    ADD CONSTRAINT actimize_alert_callbacks_pkey PRIMARY KEY (callback_id);


--
-- Name: actimize_screening_type_mappings actimize_screening_type_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actimize_screening_type_mappings
    ADD CONSTRAINT actimize_screening_type_mappings_pkey PRIMARY KEY ("Screening_Type");


--
-- Name: api_access_logs api_access_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_access_logs
    ADD CONSTRAINT api_access_logs_pkey PRIMARY KEY (access_id);


--
-- Name: app_users app_users_old_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_old_id_key UNIQUE (old_id);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (user_id);


--
-- Name: audit_events audit_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (event_id);


--
-- Name: batch_file_uploads batch_file_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_file_uploads
    ADD CONSTRAINT batch_file_uploads_pkey PRIMARY KEY (upload_id);


--
-- Name: business_unit_screening_types business_unit_screening_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_unit_screening_types
    ADD CONSTRAINT business_unit_screening_types_pkey PRIMARY KEY (business_unit_code, "Screening_Type");


--
-- Name: business_units business_units_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_units
    ADD CONSTRAINT business_units_pkey PRIMARY KEY (business_unit_code);


--
-- Name: daily_schedules daily_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_schedules
    ADD CONSTRAINT daily_schedules_pkey PRIMARY KEY (schedule_id);


--
-- Name: external_api_errors external_api_errors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_api_errors
    ADD CONSTRAINT external_api_errors_pkey PRIMARY KEY (error_id);


--
-- Name: job_items job_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_items
    ADD CONSTRAINT job_items_pkey PRIMARY KEY (job_id, item_key);


--
-- Name: job_metadata job_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_metadata
    ADD CONSTRAINT job_metadata_pkey PRIMARY KEY (job_id);


--
-- Name: job_schedule_notifications job_schedule_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_schedule_notifications
    ADD CONSTRAINT job_schedule_notifications_pkey PRIMARY KEY (job_id);


--
-- Name: jobs jobs_job_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_job_id_key UNIQUE (job_id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (job_id);


--
-- Name: schedule_notifications schedule_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_notifications
    ADD CONSTRAINT schedule_notifications_pkey PRIMARY KEY (notification_id);


--
-- Name: schedule_record_state schedule_record_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_record_state
    ADD CONSTRAINT schedule_record_state_pkey PRIMARY KEY (schedule_id, record_hash);


--
-- Name: schedule_subscriptions schedule_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_subscriptions
    ADD CONSTRAINT schedule_subscriptions_pkey PRIMARY KEY (subscription_id);


--
-- Name: user_business_units user_business_units_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_business_units
    ADD CONSTRAINT user_business_units_pkey PRIMARY KEY (user_ref_id, business_unit_code);


--
-- Name: idx_actimize_callbacks_alert_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_actimize_callbacks_alert_id ON public.actimize_alert_callbacks USING btree (alert_id, created_at);


--
-- Name: idx_actimize_callbacks_unique_key_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_actimize_callbacks_unique_key_created_at ON public.actimize_alert_callbacks USING btree (normalized_unique_key, created_at);


--
-- Name: idx_api_access_logs_correlation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_access_logs_correlation ON public.api_access_logs USING btree (correlation_id, created_at);


--
-- Name: idx_api_access_logs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_access_logs_created_at ON public.api_access_logs USING btree (created_at);


--
-- Name: idx_api_access_logs_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_access_logs_path ON public.api_access_logs USING btree (request_path, created_at);


--
-- Name: idx_api_access_logs_user_ref_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_access_logs_user_ref_created_at ON public.api_access_logs USING btree (user_ref_id, created_at DESC, access_id DESC);


--
-- Name: idx_app_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_users_email ON public.app_users USING btree (email);


--
-- Name: idx_app_users_old_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_app_users_old_id ON public.app_users USING btree (old_id);


--
-- Name: idx_audit_events_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_events_event_id ON public.audit_events USING btree (event_id DESC);


--
-- Name: idx_audit_events_user_ref_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_events_user_ref_event ON public.audit_events USING btree (user_ref_id, event_id DESC);


--
-- Name: idx_batch_file_uploads_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_batch_file_uploads_job_id ON public.batch_file_uploads USING btree (job_id);


--
-- Name: idx_batch_file_uploads_user_ref; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_batch_file_uploads_user_ref ON public.batch_file_uploads USING btree (user_ref_id, created_at DESC, upload_id);


--
-- Name: idx_business_unit_screening_types_bu_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_business_unit_screening_types_bu_active ON public.business_unit_screening_types USING btree (business_unit_code, is_active, "Screening_Type");


--
-- Name: idx_business_unit_screening_types_screening_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_business_unit_screening_types_screening_active ON public.business_unit_screening_types USING btree ("Screening_Type", is_active, business_unit_code);


--
-- Name: idx_daily_schedules_active_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daily_schedules_active_created ON public.daily_schedules USING btree (is_active, created_at DESC, schedule_id);


--
-- Name: idx_daily_schedules_next_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daily_schedules_next_run ON public.daily_schedules USING btree (next_run_at);


--
-- Name: idx_daily_schedules_queries_json_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daily_schedules_queries_json_gin ON public.daily_schedules USING gin (queries_json);


--
-- Name: idx_daily_schedules_screening_types_json_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daily_schedules_screening_types_json_gin ON public.daily_schedules USING gin (screening_types_json);


--
-- Name: idx_daily_schedules_user_ref; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daily_schedules_user_ref ON public.daily_schedules USING btree (user_ref_id, created_at DESC, schedule_id);


--
-- Name: idx_external_api_errors_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_external_api_errors_created_at ON public.external_api_errors USING btree (created_at);


--
-- Name: idx_external_api_errors_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_external_api_errors_job_id ON public.external_api_errors USING btree (job_id);


--
-- Name: idx_external_api_errors_job_item; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_external_api_errors_job_item ON public.external_api_errors USING btree (job_id, item_key, created_at);


--
-- Name: idx_external_api_errors_user_ref_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_external_api_errors_user_ref_created_at ON public.external_api_errors USING btree (user_ref_id, created_at DESC, error_id DESC);


--
-- Name: idx_job_items_item_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_items_item_key ON public.job_items USING btree (item_key);


--
-- Name: idx_job_items_job_id_parsed_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_items_job_id_parsed_status ON public.job_items USING btree (job_id, parsed_status);


--
-- Name: idx_job_items_job_id_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_items_job_id_sort ON public.job_items USING btree (job_id, updated_at DESC, item_key);


--
-- Name: idx_job_items_parsed_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_items_parsed_status ON public.job_items USING btree (parsed_status);


--
-- Name: idx_job_items_request_json_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_items_request_json_gin ON public.job_items USING gin (request_json);


--
-- Name: idx_job_items_response_json_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_items_response_json_gin ON public.job_items USING gin (response_json);


--
-- Name: idx_job_items_user_ref_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_items_user_ref_id ON public.job_items USING btree (user_ref_id);


--
-- Name: idx_job_metadata_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_job_metadata_job_id ON public.job_metadata USING btree (job_id);


--
-- Name: idx_job_schedule_notifications_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_job_schedule_notifications_job_id ON public.job_schedule_notifications USING btree (job_id);


--
-- Name: idx_jobs_job_seq_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_jobs_job_seq_id ON public.jobs USING btree (job_id);


--
-- Name: idx_jobs_user_ref; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_jobs_user_ref ON public.jobs USING btree (user_ref_id, updated_at DESC, created_at DESC, job_id);


--
-- Name: idx_mv_daily_schedule_batch_runs_job; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_mv_daily_schedule_batch_runs_job ON public.mv_daily_schedule_batch_runs USING btree (job_id);


--
-- Name: idx_mv_daily_schedule_batch_runs_sched_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mv_daily_schedule_batch_runs_sched_created ON public.mv_daily_schedule_batch_runs USING btree (schedule_id, created_at DESC, job_id);


--
-- Name: idx_mv_user_recent_results_pk; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_mv_user_recent_results_pk ON public.mv_user_recent_results USING btree (job_id, item_key);


--
-- Name: idx_mv_user_recent_results_user_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mv_user_recent_results_user_sort ON public.mv_user_recent_results USING btree (user_ref_id, sort_ts DESC, job_id, item_key);


--
-- Name: idx_mv_user_result_summary_counts_user; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_mv_user_result_summary_counts_user ON public.mv_user_result_summary_counts USING btree (user_ref_id);


--
-- Name: idx_mv_user_submission_jobs_pk; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_mv_user_submission_jobs_pk ON public.mv_user_submission_jobs USING btree (job_id);


--
-- Name: idx_mv_user_submission_jobs_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mv_user_submission_jobs_user_created ON public.mv_user_submission_jobs USING btree (user_ref_id, created_at DESC, job_id);


--
-- Name: idx_mv_user_submission_jobs_user_name_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mv_user_submission_jobs_user_name_created ON public.mv_user_submission_jobs USING btree (lower(COALESCE(NULLIF((user_name)::text, ''::text), (user_id)::text, ''::text)), created_at DESC, job_id);


--
-- Name: idx_notifications_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_email ON public.schedule_notifications USING btree (email, created_at);


--
-- Name: idx_schedule_notifications_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_schedule_notifications_job_id ON public.schedule_notifications USING btree (job_id);


--
-- Name: idx_schedule_notifications_summary_json_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_schedule_notifications_summary_json_gin ON public.schedule_notifications USING gin (summary_json);


--
-- Name: idx_schedule_notifications_user_ref; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_schedule_notifications_user_ref ON public.schedule_notifications USING btree (user_ref_id, created_at DESC, notification_id);


--
-- Name: idx_schedule_record_state_last_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_schedule_record_state_last_job_id ON public.schedule_record_state USING btree (last_job_id);


--
-- Name: idx_schedule_subscriptions_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_schedule_subscriptions_unique ON public.schedule_subscriptions USING btree (schedule_id, email);


--
-- Name: idx_schedule_subscriptions_user_ref; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_schedule_subscriptions_user_ref ON public.schedule_subscriptions USING btree (user_ref_id, created_at DESC, subscription_id);


--
-- Name: idx_user_business_units_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_business_units_code ON public.user_business_units USING btree (business_unit_code, is_active);


--
-- Name: idx_user_business_units_user_ref; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_business_units_user_ref ON public.user_business_units USING btree (user_ref_id, is_active, business_unit_code);


--
-- Name: api_access_logs fk_api_access_logs_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_access_logs
    ADD CONSTRAINT fk_api_access_logs_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- Name: audit_events fk_audit_events_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT fk_audit_events_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- Name: batch_file_uploads fk_batch_file_uploads_job_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_file_uploads
    ADD CONSTRAINT fk_batch_file_uploads_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(job_id) ON DELETE SET NULL;


--
-- Name: batch_file_uploads fk_batch_file_uploads_schedule_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_file_uploads
    ADD CONSTRAINT fk_batch_file_uploads_schedule_id FOREIGN KEY (schedule_id) REFERENCES public.daily_schedules(schedule_id) ON DELETE SET NULL;


--
-- Name: batch_file_uploads fk_batch_file_uploads_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_file_uploads
    ADD CONSTRAINT fk_batch_file_uploads_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- Name: business_unit_screening_types fk_business_unit_screening_types_business_unit_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_unit_screening_types
    ADD CONSTRAINT fk_business_unit_screening_types_business_unit_code FOREIGN KEY (business_unit_code) REFERENCES public.business_units(business_unit_code) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: business_unit_screening_types fk_business_unit_screening_types_screening_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_unit_screening_types
    ADD CONSTRAINT fk_business_unit_screening_types_screening_type FOREIGN KEY ("Screening_Type") REFERENCES public.actimize_screening_type_mappings("Screening_Type") ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: daily_schedules fk_daily_schedules_business_unit_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_schedules
    ADD CONSTRAINT fk_daily_schedules_business_unit_code FOREIGN KEY (business_unit_code) REFERENCES public.business_units(business_unit_code) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: daily_schedules fk_daily_schedules_source_upload_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_schedules
    ADD CONSTRAINT fk_daily_schedules_source_upload_id FOREIGN KEY (source_upload_id) REFERENCES public.batch_file_uploads(upload_id) ON DELETE SET NULL;


--
-- Name: daily_schedules fk_daily_schedules_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_schedules
    ADD CONSTRAINT fk_daily_schedules_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- Name: external_api_errors fk_external_api_errors_job_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_api_errors
    ADD CONSTRAINT fk_external_api_errors_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(job_id) ON DELETE SET NULL;


--
-- Name: external_api_errors fk_external_api_errors_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_api_errors
    ADD CONSTRAINT fk_external_api_errors_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- Name: job_items fk_job_items_job_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_items
    ADD CONSTRAINT fk_job_items_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(job_id) ON DELETE CASCADE;


--
-- Name: job_items fk_job_items_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_items
    ADD CONSTRAINT fk_job_items_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- Name: job_metadata fk_job_metadata_business_unit_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_metadata
    ADD CONSTRAINT fk_job_metadata_business_unit_code FOREIGN KEY (business_unit_code) REFERENCES public.business_units(business_unit_code) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: job_metadata fk_job_metadata_daily_schedule_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_metadata
    ADD CONSTRAINT fk_job_metadata_daily_schedule_id FOREIGN KEY (daily_schedule_id) REFERENCES public.daily_schedules(schedule_id) ON DELETE SET NULL;


--
-- Name: job_metadata fk_job_metadata_job_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_metadata
    ADD CONSTRAINT fk_job_metadata_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(job_id) ON DELETE CASCADE;


--
-- Name: job_schedule_notifications fk_job_schedule_notifications_job_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_schedule_notifications
    ADD CONSTRAINT fk_job_schedule_notifications_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(job_id) ON DELETE CASCADE;


--
-- Name: job_schedule_notifications fk_job_schedule_notifications_schedule_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_schedule_notifications
    ADD CONSTRAINT fk_job_schedule_notifications_schedule_id FOREIGN KEY (schedule_id) REFERENCES public.daily_schedules(schedule_id) ON DELETE CASCADE;


--
-- Name: jobs fk_jobs_source_schedule_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_source_schedule_id FOREIGN KEY (source_schedule_id) REFERENCES public.daily_schedules(schedule_id) ON DELETE SET NULL;


--
-- Name: jobs fk_jobs_source_upload_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_source_upload_id FOREIGN KEY (source_upload_id) REFERENCES public.batch_file_uploads(upload_id) ON DELETE SET NULL;


--
-- Name: jobs fk_jobs_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- Name: schedule_notifications fk_schedule_notifications_job_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_notifications
    ADD CONSTRAINT fk_schedule_notifications_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(job_id) ON DELETE SET NULL;


--
-- Name: schedule_notifications fk_schedule_notifications_schedule_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_notifications
    ADD CONSTRAINT fk_schedule_notifications_schedule_id FOREIGN KEY (schedule_id) REFERENCES public.daily_schedules(schedule_id) ON DELETE SET NULL;


--
-- Name: schedule_notifications fk_schedule_notifications_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_notifications
    ADD CONSTRAINT fk_schedule_notifications_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- Name: schedule_record_state fk_schedule_record_state_last_job_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_record_state
    ADD CONSTRAINT fk_schedule_record_state_last_job_id FOREIGN KEY (last_job_id) REFERENCES public.jobs(job_id) ON DELETE SET NULL;


--
-- Name: schedule_record_state fk_schedule_record_state_schedule_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_record_state
    ADD CONSTRAINT fk_schedule_record_state_schedule_id FOREIGN KEY (schedule_id) REFERENCES public.daily_schedules(schedule_id) ON DELETE CASCADE;


--
-- Name: schedule_subscriptions fk_schedule_subscriptions_schedule_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_subscriptions
    ADD CONSTRAINT fk_schedule_subscriptions_schedule_id FOREIGN KEY (schedule_id) REFERENCES public.daily_schedules(schedule_id) ON DELETE CASCADE;


--
-- Name: schedule_subscriptions fk_schedule_subscriptions_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_subscriptions
    ADD CONSTRAINT fk_schedule_subscriptions_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- Name: user_business_units fk_user_business_units_business_unit_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_business_units
    ADD CONSTRAINT fk_user_business_units_business_unit_code FOREIGN KEY (business_unit_code) REFERENCES public.business_units(business_unit_code) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: user_business_units fk_user_business_units_user_ref_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_business_units
    ADD CONSTRAINT fk_user_business_units_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES public.app_users(user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 1Yw289Odu8iIAL6k1LkbuDpT7ZsF2s3jpYXgCgcxysHB5PkTcAiWxQJUnFVDF8o



-- Reference Data DML

--
-- PostgreSQL database dump
--

\restrict ziRPPGlIkGZger347GeI24FLOjdOiodPiHFtdc0FfXkTdCrDtXWbzPgh7rEdf7a

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Debian 17.9-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: actimize_screening_type_mappings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_314(a)', true, '2026-04-29 00:00:00+00', '2026-05-04 19:16:08.270907+00', 'Customer FinCEN 314(a)', '314a', 2);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_AME', true, '2026-04-29 00:00:00+00', '2026-05-04 19:16:08.271898+00', 'Customer AME', 'AME', 3);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_PEP_RCA_International', true, '2026-04-29 00:00:00+00', '2026-05-04 19:16:08.272727+00', 'Political Exposed Person - Non -US', 'PEP', 4);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Marijuana_DJ_External', true, '2026-04-29 00:00:00+00', '2026-05-04 19:16:08.273527+00', 'Marijuana Screening', 'MPIN', 5);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_Customers_PEP_RCA_International', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.274474+00', 'Global Political Exposed Person', 'PEP-G', 6);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_APAC', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.275287+00', 'Customer Sanctions PGIM Real Estate (APAC) & PGIM Private Capital (Australia)', 'SAN-PAPC', 7);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_CIO', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.276174+00', 'Customer Sanctions PGIM CIO', 'SAN-PCIO', 8);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_FI', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.276965+00', 'Customer Sanctions PGIM Fixed Income', 'SAN-PFIC', 9);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions', true, '2026-04-29 00:00:00+00', '2026-05-04 19:16:08.268995+00', 'Customer Sanctions', 'SAN-US', 1);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_JK_ASC', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.27783+00', 'Customer Sanctions Jennison Associates', 'SAN-PJAC', 10);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_LATAM', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.278589+00', 'Customer Sanctions PGIM LATAM', 'SAN-PPLA', 11);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_MA', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.279318+00', 'Customer Sanctions PGIM Multi-Asset Solutions / PGIM Strategic Capital Group', 'SAN-PSCG', 12);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_NE_FI', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.28+00', 'Customer Sanctions Public & Private Fixed Income, PGIM Netherlands B.V.', 'SAN-PUPV', 13);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_Customers_Sanctions_PGIM_HK', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.280686+00', 'Customer Sanctions PGIM HongKong', 'SAN-PGHK', 14);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_Customers_Sanctions_PGIM_JAPAN', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.281451+00', 'Customer Sanctions PGIM Japan', 'SAN-PGJP', 15);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_PP_FI', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.282099+00', 'Customer Sanctions PGIM Public and Private Fixed Income', 'SAN-PPFI', 16);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_QUANT', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.282835+00', 'Customer Sanctions PGIM Quant', 'SAN-PPQS', 17);
INSERT INTO public.actimize_screening_type_mappings ("Search_Definition_ID", is_active, created_at, updated_at, search_definition_name, "Screening_Type", display_order) VALUES ('SD_US_Customers_Sanctions_PGIM_RE', true, '2026-05-02 00:00:00+00', '2026-05-04 19:16:08.284692+00', 'Customer Sanctions PGIM Real Estate', 'SAN-PLUX', 18);


--
-- Data for Name: business_units; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_OSGLI', 'OSGLI', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_VM', 'Vendor Management', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_HR', 'Human Resources', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_OPES', 'Operation/Enabling Solutions', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM', 'PGIM', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_TENANT', 'PGIM Real Estate tenant', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE', 'PGIM Real Estate', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_FI', 'PGIM Fixed Income', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_PP_FI', 'PGIMPublic and Private Fixed Income', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_MA', 'PGIM Multi Asset Solutions', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_CIO', 'PGIM CIO', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JAPAN', 'PGIM Japan', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JK_ASC', 'PGIM Jenkins Associates', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_NE_FI', 'PGIM Netherlands', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_QUANT', 'PGIM Quant Compliance', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_APAC', 'PGIM Real Estate APAC', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_LATAM', 'PGIM LATAM', true, '2026-04-17 22:48:09.326599+00', '2026-04-17 22:48:09.326599+00');
INSERT INTO public.business_units (business_unit_code, business_unit_name, is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_HK', 'PGIM HongKong', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');


--
-- Data for Name: business_unit_screening_types; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_APAC', 'SAN-PAPC', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_CIO', 'SAN-PCIO', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_FI', 'SAN-PFIC', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JK_ASC', 'SAN-PJAC', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_LATAM', 'SAN-PPLA', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_MA', 'SAN-PSCG', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_NE_FI', 'SAN-PUPV', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_HK', 'SAN-PGHK', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JAPAN', 'SAN-PGJP', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_PP_FI', 'SAN-PPFI', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_QUANT', 'SAN-PPQS', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE', 'SAN-PLUX', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_HR', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OPES', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OSGLI', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_CIO', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_FI', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_HK', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JAPAN', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JK_ASC', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_LATAM', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_MA', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_NE_FI', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_PP_FI', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_QUANT', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_APAC', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_TENANT', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_VM', 'SAN-US', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_HR', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OPES', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OSGLI', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_CIO', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_FI', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_HK', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JAPAN', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JK_ASC', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_LATAM', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_MA', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_NE_FI', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_PP_FI', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_QUANT', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_APAC', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_TENANT', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_VM', 'AME', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_HR', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OPES', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OSGLI', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_CIO', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_FI', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_HK', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JAPAN', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JK_ASC', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_LATAM', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_MA', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_NE_FI', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_PP_FI', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_QUANT', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_APAC', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_TENANT', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_VM', 'PEP-G', true, '2026-05-20 13:35:23.489831+00', '2026-05-20 13:35:23.489831+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OSGLI', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OSGLI', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OSGLI', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_VM', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_VM', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_VM', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_HR', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_HR', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_HR', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OPES', 'PEP', true, '2026-05-20 13:35:23.489831+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OPES', '314a', true, '2026-05-20 13:35:23.489831+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_OPES', 'MPIN', true, '2026-05-20 13:35:23.489831+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_TENANT', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_TENANT', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_TENANT', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_FI', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_FI', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_FI', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_PP_FI', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_PP_FI', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_PP_FI', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_MA', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_MA', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_MA', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_CIO', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_CIO', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_CIO', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JAPAN', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JAPAN', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JAPAN', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JK_ASC', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JK_ASC', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_JK_ASC', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_NE_FI', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_NE_FI', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_NE_FI', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_QUANT', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_QUANT', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_QUANT', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_APAC', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_APAC', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_RE_APAC', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_LATAM', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_LATAM', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_LATAM', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_HK', 'PEP', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_HK', '314a', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');
INSERT INTO public.business_unit_screening_types (business_unit_code, "Screening_Type", is_active, created_at, updated_at) VALUES ('US_PRU_PGIM_HK', 'MPIN', true, '2026-05-22 13:57:09.900222+00', '2026-05-22 13:57:09.900222+00');


--
-- PostgreSQL database dump complete
--

\unrestrict ziRPPGlIkGZger347GeI24FLOjdOiodPiHFtdc0FfXkTdCrDtXWbzPgh7rEdf7a


