-- Roles and grants
-- Generated at: 2026-03-14T23:21:14.324725+00:00
-- Schema: dbacd

-- Role definitions (passwords excluded)
CREATE ROLE "rds_ad" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "rds_extension" WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "rds_iam" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "rds_password" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "rds_replication" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "rds_reserved" WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "rds_superuser" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "rdsadmin" WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "screening_admin" WITH NOSUPERUSER INHERIT CREATEROLE CREATEDB LOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;

-- Role memberships
GRANT "rds_password" TO "rds_superuser" WITH ADMIN OPTION;
GRANT "rds_replication" TO "rds_superuser" WITH ADMIN OPTION;
GRANT "rds_superuser" TO "screening_admin";

-- Schema grants for dbacd
GRANT CREATE ON SCHEMA dbacd TO "screening_admin";
GRANT USAGE ON SCHEMA dbacd TO "screening_admin";

-- Table grants for dbacd
GRANT DELETE ON TABLE dbacd."api_access_logs" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."api_access_logs" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."api_access_logs" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."api_access_logs" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."api_access_logs" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."api_access_logs" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."api_access_logs" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."api_access_logs" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."audit_events" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."audit_events" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."audit_events" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."audit_events" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."audit_events" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."audit_events" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."audit_events" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."audit_events" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."batch_file_uploads" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."batch_file_uploads" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."batch_file_uploads" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."batch_file_uploads" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."batch_file_uploads" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."batch_file_uploads" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."batch_file_uploads" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."batch_file_uploads" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."business_units" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."business_units" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."business_units" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."business_units" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."business_units" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."business_units" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."business_units" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."business_units" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."daily_schedules" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."daily_schedules" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."daily_schedules" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."daily_schedules" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."daily_schedules" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."daily_schedules" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."daily_schedules" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."daily_schedules" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."external_api_errors" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."external_api_errors" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."external_api_errors" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."external_api_errors" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."external_api_errors" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."external_api_errors" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."external_api_errors" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."external_api_errors" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."job_items" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."job_items" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."job_items" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."job_items" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."job_items" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."job_items" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."job_items" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."job_items" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."job_metadata" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."job_metadata" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."job_metadata" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."job_metadata" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."job_metadata" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."job_metadata" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."job_metadata" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."job_metadata" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."job_schedule_notifications" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."job_schedule_notifications" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."job_schedule_notifications" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."job_schedule_notifications" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."job_schedule_notifications" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."job_schedule_notifications" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."job_schedule_notifications" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."job_schedule_notifications" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."jobs" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."jobs" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."jobs" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."jobs" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."jobs" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."jobs" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."jobs" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."jobs" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."schedule_notifications" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."schedule_notifications" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."schedule_notifications" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."schedule_notifications" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."schedule_notifications" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."schedule_notifications" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."schedule_notifications" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."schedule_notifications" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."schedule_record_state" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."schedule_record_state" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."schedule_record_state" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."schedule_record_state" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."schedule_record_state" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."schedule_record_state" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."schedule_record_state" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."schedule_record_state" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."schedule_subscriptions" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."schedule_subscriptions" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."schedule_subscriptions" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."schedule_subscriptions" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."schedule_subscriptions" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."schedule_subscriptions" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."schedule_subscriptions" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."schedule_subscriptions" TO "screening_admin";
GRANT DELETE ON TABLE dbacd."user_business_units" TO "screening_admin";
GRANT INSERT ON TABLE dbacd."user_business_units" TO "screening_admin";
GRANT MAINTAIN ON TABLE dbacd."user_business_units" TO "screening_admin";
GRANT REFERENCES ON TABLE dbacd."user_business_units" TO "screening_admin";
GRANT SELECT ON TABLE dbacd."user_business_units" TO "screening_admin";
GRANT TRIGGER ON TABLE dbacd."user_business_units" TO "screening_admin";
GRANT TRUNCATE ON TABLE dbacd."user_business_units" TO "screening_admin";
GRANT UPDATE ON TABLE dbacd."user_business_units" TO "screening_admin";

-- Sequence grants for dbacd
GRANT USAGE ON SEQUENCE dbacd."api_access_logs_access_id_seq" TO "screening_admin";
GRANT USAGE ON SEQUENCE dbacd."audit_events_event_id_seq" TO "screening_admin";
GRANT USAGE ON SEQUENCE dbacd."external_api_errors_error_id_seq" TO "screening_admin";
GRANT USAGE ON SEQUENCE dbacd."schedule_notifications_notification_id_seq" TO "screening_admin";
