BEGIN;

CREATE TABLE IF NOT EXISTS app_users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  name TEXT,
  email TEXT,
  old_id TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_app_users_old_id ON app_users(old_id);
CREATE INDEX IF NOT EXISTS idx_app_users_email ON app_users(email);

ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS user_ref_id BIGINT;
ALTER TABLE IF EXISTS daily_schedules ADD COLUMN IF NOT EXISTS user_ref_id BIGINT;
ALTER TABLE IF EXISTS batch_file_uploads ADD COLUMN IF NOT EXISTS user_ref_id BIGINT;
ALTER TABLE IF EXISTS schedule_subscriptions ADD COLUMN IF NOT EXISTS user_ref_id BIGINT;
ALTER TABLE IF EXISTS schedule_notifications ADD COLUMN IF NOT EXISTS user_ref_id BIGINT;
ALTER TABLE IF EXISTS user_business_units ADD COLUMN IF NOT EXISTS user_ref_id BIGINT;
ALTER TABLE IF EXISTS audit_events ADD COLUMN IF NOT EXISTS user_ref_id BIGINT;
ALTER TABLE IF EXISTS external_api_errors ADD COLUMN IF NOT EXISTS user_ref_id BIGINT;
ALTER TABLE IF EXISTS api_access_logs ADD COLUMN IF NOT EXISTS user_ref_id BIGINT;

WITH raw_users AS (
  SELECT NULLIF(BTRIM(user_id), '') AS old_id, NULL::TEXT AS user_name, NULL::TEXT AS user_email
  FROM jobs
  UNION ALL
  SELECT NULLIF(BTRIM(user_id), ''), NULL::TEXT, NULL::TEXT FROM daily_schedules
  UNION ALL
  SELECT NULLIF(BTRIM(user_id), ''), NULL::TEXT, NULL::TEXT FROM batch_file_uploads
  UNION ALL
  SELECT NULLIF(BTRIM(user_id), ''), NULL::TEXT, NULLIF(LOWER(BTRIM(email)), '') FROM schedule_subscriptions
  UNION ALL
  SELECT NULLIF(BTRIM(user_id), ''), NULLIF(BTRIM(user_name), ''), NULLIF(LOWER(BTRIM(email)), '') FROM schedule_notifications
  UNION ALL
  SELECT NULLIF(BTRIM(user_id), ''), NULL::TEXT, NULL::TEXT FROM user_business_units
  UNION ALL
  SELECT NULLIF(BTRIM(user_id), ''), NULLIF(BTRIM(user_name), ''), NULL::TEXT FROM audit_events
  UNION ALL
  SELECT NULLIF(BTRIM(user_id), ''), NULLIF(BTRIM(user_name), ''), NULL::TEXT FROM external_api_errors
  UNION ALL
  SELECT NULLIF(BTRIM(user_id), ''), NULLIF(BTRIM(user_name), ''), NULL::TEXT FROM api_access_logs
), ranked AS (
  SELECT
    old_id,
    user_name,
    user_email,
    ROW_NUMBER() OVER (
      PARTITION BY old_id
      ORDER BY
        CASE WHEN user_name IS NULL OR user_name = '' THEN 1 ELSE 0 END,
        CASE WHEN user_email IS NULL OR user_email = '' THEN 1 ELSE 0 END,
        user_name,
        user_email
    ) AS rn
  FROM raw_users
  WHERE old_id IS NOT NULL
)
INSERT INTO app_users(old_id, name, email, is_active, created_at, updated_at)
SELECT
  old_id,
  user_name,
  user_email,
  TRUE,
  NOW(),
  NOW()
FROM ranked
WHERE rn = 1
ON CONFLICT(old_id)
DO UPDATE SET
  name = COALESCE(EXCLUDED.name, app_users.name),
  email = COALESCE(EXCLUDED.email, app_users.email),
  is_active = TRUE,
  updated_at = NOW();

UPDATE jobs j
SET user_ref_id = u.user_id
FROM app_users u
WHERE j.user_ref_id IS NULL
  AND NULLIF(BTRIM(j.user_id), '') IS NOT NULL
  AND u.old_id = BTRIM(j.user_id);

UPDATE daily_schedules d
SET user_ref_id = u.user_id
FROM app_users u
WHERE d.user_ref_id IS NULL
  AND NULLIF(BTRIM(d.user_id), '') IS NOT NULL
  AND u.old_id = BTRIM(d.user_id);

UPDATE batch_file_uploads b
SET user_ref_id = u.user_id
FROM app_users u
WHERE b.user_ref_id IS NULL
  AND NULLIF(BTRIM(b.user_id), '') IS NOT NULL
  AND u.old_id = BTRIM(b.user_id);

UPDATE schedule_subscriptions s
SET user_ref_id = u.user_id
FROM app_users u
WHERE s.user_ref_id IS NULL
  AND NULLIF(BTRIM(s.user_id), '') IS NOT NULL
  AND u.old_id = BTRIM(s.user_id);

UPDATE schedule_notifications n
SET user_ref_id = u.user_id
FROM app_users u
WHERE n.user_ref_id IS NULL
  AND NULLIF(BTRIM(n.user_id), '') IS NOT NULL
  AND u.old_id = BTRIM(n.user_id);

UPDATE user_business_units ubu
SET user_ref_id = u.user_id
FROM app_users u
WHERE ubu.user_ref_id IS NULL
  AND NULLIF(BTRIM(ubu.user_id), '') IS NOT NULL
  AND u.old_id = BTRIM(ubu.user_id);

UPDATE audit_events a
SET user_ref_id = u.user_id
FROM app_users u
WHERE a.user_ref_id IS NULL
  AND NULLIF(BTRIM(a.user_id), '') IS NOT NULL
  AND u.old_id = BTRIM(a.user_id);

UPDATE external_api_errors e
SET user_ref_id = u.user_id
FROM app_users u
WHERE e.user_ref_id IS NULL
  AND NULLIF(BTRIM(e.user_id), '') IS NOT NULL
  AND u.old_id = BTRIM(e.user_id);

UPDATE api_access_logs l
SET user_ref_id = u.user_id
FROM app_users u
WHERE l.user_ref_id IS NULL
  AND NULLIF(BTRIM(l.user_id), '') IS NOT NULL
  AND u.old_id = BTRIM(l.user_id);

CREATE INDEX IF NOT EXISTS idx_jobs_user_ref
  ON jobs(user_ref_id, updated_at DESC, created_at DESC, job_id);

CREATE INDEX IF NOT EXISTS idx_daily_schedules_user_ref
  ON daily_schedules(user_ref_id, created_at DESC, schedule_id);

CREATE INDEX IF NOT EXISTS idx_batch_file_uploads_user_ref
  ON batch_file_uploads(user_ref_id, created_at DESC, upload_id);

CREATE INDEX IF NOT EXISTS idx_schedule_subscriptions_user_ref
  ON schedule_subscriptions(user_ref_id, created_at DESC, subscription_id);

CREATE INDEX IF NOT EXISTS idx_schedule_notifications_user_ref
  ON schedule_notifications(user_ref_id, created_at DESC, notification_id);

CREATE INDEX IF NOT EXISTS idx_user_business_units_user_ref
  ON user_business_units(user_ref_id, is_active, business_unit_code);

CREATE INDEX IF NOT EXISTS idx_audit_events_user_ref_event
  ON audit_events(user_ref_id, event_id DESC);

CREATE INDEX IF NOT EXISTS idx_external_api_errors_user_ref_created_at
  ON external_api_errors(user_ref_id, created_at DESC, error_id DESC);

CREATE INDEX IF NOT EXISTS idx_api_access_logs_user_ref_created_at
  ON api_access_logs(user_ref_id, created_at DESC, access_id DESC);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_matviews
    WHERE schemaname = current_schema()
      AND matviewname = 'mv_user_recent_results'
  ) THEN
    EXECUTE 'REFRESH MATERIALIZED VIEW mv_user_recent_results';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_matviews
    WHERE schemaname = current_schema()
      AND matviewname = 'mv_user_result_summary_counts'
  ) THEN
    EXECUTE 'REFRESH MATERIALIZED VIEW mv_user_result_summary_counts';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_matviews
    WHERE schemaname = current_schema()
      AND matviewname = 'mv_daily_schedule_batch_runs'
  ) THEN
    EXECUTE 'REFRESH MATERIALIZED VIEW mv_daily_schedule_batch_runs';
  END IF;
END $$;

COMMIT;
