BEGIN;

ALTER TABLE IF EXISTS app_users
  ALTER COLUMN name TYPE VARCHAR(255)
  USING CASE
    WHEN name IS NULL THEN NULL
    ELSE LEFT(name, 255)
  END;

ALTER TABLE IF EXISTS app_users
  ALTER COLUMN email TYPE VARCHAR(50)
  USING CASE
    WHEN email IS NULL THEN NULL
    ELSE LEFT(email, 50)
  END;

COMMIT;
