/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as ManageUsersRouteImport } from './routes/manage-users'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as DailySchedulesRouteImport } from './routes/daily-schedules'
import { Route as IndexRouteImport } from './routes/index'

const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUsersRoute = ManageUsersRouteImport.update({
  id: '/manage-users',
  path: '/manage-users',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const DailySchedulesRoute = DailySchedulesRouteImport.update({
  id: '/daily-schedules',
  path: '/daily-schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily-schedules': typeof DailySchedulesRoute
  '/intro': typeof IntroRoute
  '/manage-users': typeof ManageUsersRoute
  '/screening': typeof ScreeningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily-schedules': typeof DailySchedulesRoute
  '/intro': typeof IntroRoute
  '/manage-users': typeof ManageUsersRoute
  '/screening': typeof ScreeningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily-schedules': typeof DailySchedulesRoute
  '/intro': typeof IntroRoute
  '/manage-users': typeof ManageUsersRoute
  '/screening': typeof ScreeningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily-schedules'
    | '/intro'
    | '/manage-users'
    | '/screening'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daily-schedules' | '/intro' | '/manage-users' | '/screening'
  id:
    | '__root__'
    | '/'
    | '/daily-schedules'
    | '/intro'
    | '/manage-users'
    | '/screening'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailySchedulesRoute: typeof DailySchedulesRoute
  IntroRoute: typeof IntroRoute
  ManageUsersRoute: typeof ManageUsersRoute
  ScreeningRoute: typeof ScreeningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-users': {
      id: '/manage-users'
      path: '/manage-users'
      fullPath: '/manage-users'
      preLoaderRoute: typeof ManageUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-schedules': {
      id: '/daily-schedules'
      path: '/daily-schedules'
      fullPath: '/daily-schedules'
      preLoaderRoute: typeof DailySchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailySchedulesRoute: DailySchedulesRoute,
  IntroRoute: IntroRoute,
  ManageUsersRoute: ManageUsersRoute,
  ScreeningRoute: ScreeningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
